from cache import InMemoryCache

if __name__ == "__main__":
    my_cache = InMemoryCache()
    status = my_cache.add("city1", "Delhi", 5)
    print(status)
    status = my_cache.add("city2", "Mumbai", 5)
    print(status)
    status = my_cache.add("city3", "Pune", 5)
    print(status)
    status = my_cache.add("city4", "Kolkata", 5)
    print(status)
    status = my_cache.size()
    print(f"Cache Size: {status}")
    my_cache.print()
    status = my_cache.get("city")
    print(status)
    status = my_cache.update("city", "Los Angeles", 10)
    print(status)
    my_cache.print()
    status = my_cache.delete("city")
    print(status)
    status = my_cache.size()
    print(f"Cache Size: {status}")
    my_cache.print()
    status = my_cache.get("city")
    print(status)
    status = my_cache.add("country", "USA", 3)
    print(status)
    my_cache.print()
    import time
    time.sleep(4)
    status = my_cache.cleanup()
    print(status)
    my_cache.print()
    status = my_cache.get("country")
    print(status)


